name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wrap dependencies and source code into a zip file
        run: |
          mkdir -p temp
          cp -r $(python -c "import site; print(site.getsitepackages()[0])")/* temp/
          cp -r app temp/
          echo "After copy:"
          ls -la temp/
          zip -r9q function.zip temp/
          rm -rf temp/
          echo "After zip:"
          ls -la
        
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        # need to add "github-actions[bot]" account in the list of collaborators or teams.
        run: |
          git config --global user.name "Bohdan Stratila"
          git config --global user.email "stratila@users.noreply.github.com"
          terraform init
          if [[ -n "$(git status --porcelain .terraform.lock.hcl)" ]]; then
            git add .terraform.lock.hcl
            git commit -m "Update Terraform lock file"
            git push
          fi

      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Format
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
